# Generated by Django 2.1.7 on 2019-03-07 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=30)),
                ('Image', models.URLField(blank=True, null=True)),
                ('Video', models.URLField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createdBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdOn'],
            },
        ),
    ]
