# Generated by Django 2.1.7 on 2019-03-21 10:07

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedflagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdBy', models.CharField(max_length=30, null=True)),
                ('title', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=150)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('Image', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=1000, validators=[django.core.validators.URLValidator]), blank=True, default=list, size=None)),
                ('Video', models.URLField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-createdOn'],
            },
        ),
    ]
