# Generated by Django 2.1.7 on 2019-03-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedflagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=30)),
                ('Image', models.URLField(blank=True, null=True)),
                ('Video', models.URLField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-createdOn'],
            },
        ),
        migrations.RemoveField(
            model_name='incident',
            name='createdBy',
        ),
        migrations.DeleteModel(
            name='Incident',
        ),
    ]
