# Generated by Django 2.1.7 on 2019-03-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redflagmodel',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redflagmodel',
            name='linkedIn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redflagmodel',
            name='mail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='redflagmodel',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
