# Generated by Django 2.1.7 on 2019-03-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_auto_20190311_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redflagmodel',
            name='incident_type',
        ),
    ]
