# Generated by Django 2.1.7 on 2019-03-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_remove_redflagmodel_incident_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='redflagmodel',
            name='createdBy',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
