# Generated by Django 2.1.7 on 2019-03-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_redflagmodel_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redflagmodel',
            name='createdBy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
