# Generated by Django 2.1.7 on 2019-03-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_redflagmodel_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redflagmodel',
            name='status',
            field=models.CharField(default='under investigation', max_length=30),
        ),
    ]
