# Generated by Django 2.1.7 on 2019-03-19 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_auto_20190315_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redflagmodel',
            name='Image',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
