# Generated by Django 2.1.7 on 2019-03-19 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_auto_20190315_1647'),
        ('incidents', '0005_auto_20190316_2016'),
    ]

    operations = [
    ]
