# Generated by Django 2.1.7 on 2019-03-20 01:06

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_auto_20190319_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redflagmodel',
            name='Image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=1000, validators=[django.core.validators.URLValidator]), blank=True, default=list, size=None),
        ),
    ]
