# Generated by Django 2.1.7 on 2019-03-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0008_auto_20190320_0106'),
        ('incidents', '0007_merge_20190319_0157'),
    ]

    operations = [
    ]
