# Generated by Django 2.1.7 on 2019-03-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_merge_20190320_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redflagmodel',
            name='status',
            field=models.CharField(default='draft', max_length=30),
        ),
    ]
