# Generated by Django 2.1.7 on 2019-03-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdBy', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('Image', models.URLField(blank=True, null=True)),
                ('Video', models.URLField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-createdOn'],
            },
        ),
    ]
