# Generated by Django 2.1.7 on 2019-03-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0004_auto_20190318_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionsmodel',
            name='Image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='interventionsmodel',
            name='Video',
            field=models.URLField(blank=True, default=''),
        ),
    ]
