# Generated by Django 2.1.7 on 2019-03-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0006_auto_20190318_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionsmodel',
            name='Image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='interventionsmodel',
            name='Video',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
