# Generated by Django 2.1.7 on 2019-03-20 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0008_imagesmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesmodel',
            name='intervention',
        ),
        migrations.DeleteModel(
            name='ImagesModel',
        ),
    ]
