# Generated by Django 2.1.7 on 2019-03-20 10:12

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0009_auto_20190320_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionsmodel',
            name='Image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=1000, validators=[django.core.validators.URLValidator]), blank=True, default=list, size=None),
        ),
    ]
