# Generated by Django 2.1.7 on 2019-03-20 14:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0010_auto_20190320_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionsmodel',
            name='Image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=1000), blank=True, default=list, size=None),
        ),
    ]
